version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - url-shortener/.env
    depends_on:
      - db
    volumes:
      - ./url-shortener:/app/url-shortener
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8080 --reload"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-neondb}
      POSTGRES_USER: ${DB_USER:-neondb_owner}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-npg_y8NzMdbsZ1rC}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
